"""Paper-facing LaTeX tables from the review campaign CSVs (model called TSD).

    python -m exp.review.make_tex --rv results/review_2026_09_22 --out results/review_2026_09_22/tables_review.tex
"""
import argparse
import os

import numpy as np
import pandas as pd

ARM_LABEL = {"tsd": "TSD (memory-conditioned incidence maps)", "current-only-maps": "Current-only maps",
             "identity-maps": "Identity maps", "gru-ordinary": "GRU + ordinary propagation",
             "diagssm-ordinary": "Diagonal SSM + ordinary propagation", "attention-gates": "History-conditioned edge gates",
             "node-frame": "Node-frame geometry", "core-off": "Core off + REC (head only)"}
ORDER = ["tsd", "current-only-maps", "identity-maps", "gru-ordinary", "diagssm-ordinary", "attention-gates", "node-frame", "core-off"]


def fmt(x, d=3):
    return "--" if pd.isna(x) else f"{x:.{d}f}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rv", default="results/review_2026_09_22"); ap.add_argument("--out", default=None)
    a = ap.parse_args()
    rv = a.rv
    runs = pd.read_csv(f"{rv}/per_seed_results.csv")
    try:
        pc = pd.read_csv(f"{rv}/paired_contrasts.csv")
    except (FileNotFoundError, pd.errors.EmptyDataError):
        pc = pd.DataFrame()
    lines = ["% Auto-generated by exp/review/make_tex.py from " + rv, "% Metric: test MRR (official negatives), mean +/- sample SD over seeds; paired delta = arm - TSD on the same seeds.", ""]
    for (ds, group, rec), g in runs[(~runs.is_audit) & (runs.group != "smoke")].groupby(["dataset", "group", "rec"]):
        # lock: for each arm, the lr with the most seeds (wave 2 lr); report that lr
        rows = []
        for arm in ORDER:
            ga = g[g.arm == arm]
            if ga.empty:
                rows.append((arm, None)); continue
            lr = ga.groupby("lr").seed.count().idxmax()
            ga = ga[ga.lr == lr].drop_duplicates("seed")
            d = pc[(pc.dataset == ds) & (pc.group == group) & (pc.rec == rec) & (pc.arm == arm) & (pc.arm_lr == lr)] if len(pc) else pd.DataFrame()
            rows.append((arm, dict(lr=lr, n=len(ga), mean=ga.test_mrr.mean(), sd=ga.test_mrr.std(ddof=1) if len(ga) > 1 else np.nan,
                                   seeds=",".join(str(s) for s in sorted(ga.seed)), params=int(ga.params_active.median()) if "params_active" in ga else None,
                                   delta=d.delta_arm_minus_tsd_mean.iloc[0] if len(d) else np.nan, dsd=d.delta_sd.iloc[0] if len(d) else np.nan,
                                   half=d.t95_halfwidth.iloc[0] if len(d) else np.nan, signs=d.signs.iloc[0] if len(d) else "")))
        lines += [f"\\begin{{table}}[t]\\centering\\small", f"\\caption{{Matched controls on {ds} ({group}, REC {rec}): test MRR over seeds and paired difference to TSD (same seeds, identical data, negatives, protocol and selection rule; lr locked per arm on seed-43 tracking validation). Active parameters exclude parameters unused by construction.}}",
                  "\\begin{tabular}{lcccrll}\\toprule", "Arm & lr & seeds & active params & mean $\\pm$ SD & $\\Delta$ vs TSD (mean $\\pm$ SD; 95\\% t) & signs \\\\ \\midrule"]
        for arm, r in rows:
            if r is None:
                lines.append(f"{ARM_LABEL[arm]} & \\multicolumn{{6}}{{l}}{{not evaluated}} \\\\"); continue
            delta = "--" if arm == "tsd" or pd.isna(r["delta"]) else f"{r['delta']:+.4f} $\\pm$ {fmt(r['dsd'],4)}; $\\pm${fmt(r['half'],4)}"
            lines.append(f"{ARM_LABEL[arm]} & {r['lr']} & {r['n']} ({r['seeds']}) & {r['params'] if r['params'] else '--'} & {fmt(r['mean'])} $\\pm$ {fmt(r['sd'])} & {delta} & {r['signs']} \\\\")
        lines += ["\\bottomrule\\end{tabular}\\end{table}", ""]
    aud = runs[runs.is_audit]
    if len(aud):
        lines += ["\\begin{table}[t]\\centering\\small", "\\caption{P0 checkpoint-replay audit of the retained headline runs: replayed test MRR vs the retained metric, and the number of queries with any non-finite positive or negative logit (before substitution).}",
                  "\\begin{tabular}{llrrrr}\\toprule", "Run & dataset & replayed test MRR & retained & difference & affected queries \\\\ \\midrule"]
        for _, r in aud.sort_values(["dataset", "seed"]).iterrows():
            name = r.run.replace("_", "\\_")
            lines.append(f"{name} & {r.dataset} & {fmt(r.test_mrr, 4)} & {fmt(r.get('retained_test_mrr', np.nan), 4)} & {fmt(r.get('replay_minus_retained_test', np.nan), 5)} & {int(r.query_audit_affected_total) if not pd.isna(r.query_audit_affected_total) else '--'} \\\\")
        lines += ["\\bottomrule\\end{tabular}\\end{table}", ""]
    out = a.out or f"{rv}/tables_review.tex"
    open(out, "w").write("\n".join(lines) + "\n")
    print(f"wrote {out} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
